"""initial schema

Revision ID: 8d5183160afc
Revises: 
Create Date: 2026-08-13 18:43:20.909991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d5183160afc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disease_dict',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('keyword', sa.String(length=100), nullable=True, comment='病历中匹配的关键词'),
    sa.Column('disease_name', sa.String(length=100), nullable=True, comment='标准化疾病名称'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_disease_dict'))
    )
    op.create_table('medical_knowledge',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('disease_name', sa.String(length=100), nullable=True, comment='疾病名称'),
    sa.Column('guide_content', sa.Text(), nullable=True, comment='临床指南内容'),
    sa.Column('vector_id', sa.String(length=100), nullable=True, comment='Milvus向量索引ID'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_medical_knowledge'))
    )
    op.create_table('medical_paper',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('paper_name', sa.String(length=200), nullable=True, comment='文献标题'),
    sa.Column('file_path', sa.String(length=255), nullable=True, comment='PDF文件路径'),
    sa.Column('full_text', sa.Text(), nullable=True, comment='PDF提取的全文内容'),
    sa.Column('ai_summary', sa.Text(), nullable=True, comment='AI生成摘要'),
    sa.Column('core_conclusion', sa.Text(), nullable=True, comment='核心研究结论'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_medical_paper'))
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False, comment='登录名'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='密码哈希'),
    sa.Column('real_name', sa.String(length=50), nullable=True, comment='真实姓名'),
    sa.Column('role', sa.String(length=20), nullable=True, comment='角色: admin/doctor/patient'),
    sa.Column('department', sa.String(length=100), nullable=True, comment='科室'),
    sa.Column('is_active', sa.Integer(), nullable=True, comment='是否启用: 1启用 0禁用'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('username', name=op.f('uq_user_username'))
    )
    op.create_table('consult_session',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True, comment='对话标题（首句摘要）'),
    sa.Column('department', sa.String(length=50), nullable=True, comment='问诊科室'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='用户ID'),
    sa.Column('message_count', sa.Integer(), nullable=True, comment='消息数'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_consult_session_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consult_session'))
    )
    op.create_index(op.f('ix_consult_session_user_id'), 'consult_session', ['user_id'], unique=False)
    op.create_table('patient',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('name', sa.String(length=50), nullable=True, comment='患者姓名'),
    sa.Column('age', sa.Integer(), nullable=True, comment='年龄'),
    sa.Column('gender', sa.String(length=10), nullable=True, comment='性别'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='联系电话'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='关联用户ID（患者角色关联）'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_patient_user_id_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patient'))
    )
    op.create_index(op.f('ix_patient_phone'), 'patient', ['phone'], unique=False)
    op.create_index(op.f('ix_patient_user_id'), 'patient', ['user_id'], unique=False)
    op.create_table('consult_message',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True, comment='会话ID'),
    sa.Column('role', sa.String(length=20), nullable=True, comment='user/assistant'),
    sa.Column('content', sa.Text(), nullable=True, comment='消息内容'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['consult_session.id'], name=op.f('fk_consult_message_session_id_consult_session'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consult_message'))
    )
    op.create_index(op.f('ix_consult_message_session_id'), 'consult_message', ['session_id'], unique=False)
    op.create_table('medical_record',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True, comment='关联患者ID'),
    sa.Column('raw_text', sa.Text(), nullable=True, comment='原始自由文本病历'),
    sa.Column('structured_data', sa.JSON(), nullable=True, comment='AI结构化抽取结果（症状、病史、诊断）'),
    sa.Column('dicom_file_path', sa.String(length=255), nullable=True, comment='DICOM影像存储路径'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], name=op.f('fk_medical_record_patient_id_patient'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_medical_record'))
    )
    op.create_index(op.f('ix_medical_record_patient_id'), 'medical_record', ['patient_id'], unique=False)
    op.create_table('diagnosis_report',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=True, comment='关联病历ID'),
    sa.Column('image_analysis', sa.Text(), nullable=True, comment='影像分析结果'),
    sa.Column('diagnosis_suggest', sa.Text(), nullable=True, comment='AI鉴别诊断建议'),
    sa.Column('pdf_path', sa.String(length=255), nullable=True, comment='导出PDF报告路径'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['record_id'], ['medical_record.id'], name=op.f('fk_diagnosis_report_record_id_medical_record'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_diagnosis_report'))
    )
    op.create_index(op.f('ix_diagnosis_report_record_id'), 'diagnosis_report', ['record_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_diagnosis_report_record_id'), table_name='diagnosis_report')
    op.drop_table('diagnosis_report')
    op.drop_index(op.f('ix_medical_record_patient_id'), table_name='medical_record')
    op.drop_table('medical_record')
    op.drop_index(op.f('ix_consult_message_session_id'), table_name='consult_message')
    op.drop_table('consult_message')
    op.drop_index(op.f('ix_patient_user_id'), table_name='patient')
    op.drop_index(op.f('ix_patient_phone'), table_name='patient')
    op.drop_table('patient')
    op.drop_index(op.f('ix_consult_session_user_id'), table_name='consult_session')
    op.drop_table('consult_session')
    op.drop_table('user')
    op.drop_table('medical_paper')
    op.drop_table('medical_knowledge')
    op.drop_table('disease_dict')
    # ### end Alembic commands ###
